[package]
name = "wolrdgen-voxels"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
bevy_app = "0.16.1"
bevy_ecs = "0.16.1"
itertools = "0.14.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
winit = "0.30.11"
